### ISSUE TITLE
 Failed to add Channel XXXX with URL 

### ISSUE THREAD

**Issue by Apoc70** [jflieben/assortedFunctionsV2#9] opened 2024-11-15 08:14 UTC
The module fails to add channels with Smiley characters as the first character. 
This seems to be a PnP-module error.
Maybe the module can catch this error?

![image](https://github.com/user-attachments/assets/12fae54e-2bd1-48d8-853c-695112d9a673)

**Comment by jflieben** [comment] 2024-11-15 08:53
@Apoc70 thanks for reporting! I just quickly tried to reproduce this, but the emoticon doesn't render in my teams client:

![image](https://github.com/user-attachments/assets/6035fec1-2dfe-427e-9844-3f17867805bb)

How did you get that emoticon in the channel name / how can I reproduce?

**Comment by jflieben** [comment] 2024-11-15 09:02
hmm no issue here, but maybe because I added the emoticon post-creation:
![image](https://github.com/user-attachments/assets/75ca2752-a882-402a-9997-960c5bf3f3c1)
I'll try another few

**Comment by jflieben** [comment] 2024-11-15 09:08
@Apoc70 still unable to reproduce, works fine here.....do those channels/sites still exist? Maybe they were deleted or something else?

**Comment by jflieben** [comment] 2024-11-15 09:15
ok, tried deleting the underlying sharepoint site of one of those channels (without deleting the channel) and got the exact same error as you're seeing above: 

`Write-Error: Failed to add Channel 🤣👍 two emoticons then with URL https://lieben.sharepoint.com/sites/TestSpoPerms2-twoemoticonsthen to scan list because Get-PnPTenantSite failed with Cannot get site https://lieben.sharepoint.com/sites/TestSpoPerms2-twoemoticonsthen.`

I think that means we can close this with 'it's a feature', let me know if you disagree or if your situation is different and feel free to reopen.

**Closed by jflieben** 2024-11-15 09:15 UTC

**Comment by Apoc70** [comment] 2024-11-15 09:21
@jflieben There is a different reason.
PnP tries to access https://TENANT.sharepoint.com/**sites**/SITENAME
which results in a 404 error.

The correct URL is
https://TENANT.sharepoint.com/**teams**/SITENAME

**Comment by jflieben** [comment] 2024-11-15 09:36
@Apoc70 thanks! That got me on the right track, as my and my customer's envs don't use that /teams/ url component I hardcoded /sites/. Fixed here: https://github.com/jflieben/assortedFunctionsV2/commit/6b0ea22b73bbc92992454122d4c794a3fd209853#diff-65d070bda006e76f0e91d92b028e6544af8a38b7a5b26dd8d3f36ed58ceeb48cR86

It'll be included in v1.0.4!
